meta:
  title: HPE Redfish Developer Portal 
  description:  HPE Redfish API implementation documentations.
  siteUrl: https://developer.hpe.com

#headerIcon: ./images/hpe.svg
logo: ./images/hpe.svg
enableToc: true
tocMaxDepth: 2
oasDefinitions:
  # add links to definitions in the Redocly API registry by using a fully qualified URL.
  # See https://redoc.ly/docs/workflows/api-registry/snapshots/#finding-your-snapshot-links
  # 
  # The following URL comes from the redfishiLO5RefDoc API Registry --> Default branch --> Download in clipboard
  # The key name (redfishiLO5RefDoc) corresponds to the definitionId key in "openapi/redfishiLO5RefDoc.page.yaml" file
  redfishiLO5RefDoc: https://api.redoc.ly/registry/hpe/redfishiLO5RefDoc/v1Alpha1/bundle/main/openapi.yaml 
  #redfishDmtfRefDoc: https://api.redoc.ly/registry/hpe/RedfishDmtfRefDoc/internalv1/bundle/main/openapi.yaml
  #redfishSuperdome280:  https://TBD
  #redfishAmplifierPack: https://TBD
  #

stylesheets:
  - https://fonts.googleapis.com/css?family=Roboto:300,400,600,700
  - https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700&display=swap

nav:

  - label: Redfish Standard
    href: 'https://www.dmtf.org/standards/redfish'
    external: true

  - label: About
    href: 'https://hpe.com/'
    external: true

  - search: true

footer:
  copyrightText: © Copyright 2017-2021 Hewlett Packard Enterprise Development LP
  columns:
    - group:
      items:
        - label: Privacy Policy
          href: 'https://www.hpe.com/us/en/legal/privacy.html'
          external: true
        - label: Cookies
          href: 'https://www.hpe.com/us/en/legal/privacy.html#accordion-accordioncontainerco-4'
          external: true
        - label: Terms of Use
          href: 'https://www.hpe.com/us/en/about/legal/terms-of-use.html'
          external: true
        - label: Do Not Sell My Personal Information
          href: 'https://www.hpe.com/us/en/privacy/personal-information.html'
          external: true

