meta:
  title: HPE Redfish Developer Central 
  description:  HPE Redfish API implementations documentation.
  siteUrl: https://www.hpe.com
headerIcon: ./images/hpe.svg
enableToc: true
oasDefinitions:
  caas-latest: https://api.redoc.ly/registry/hpe/HPE%20GreenLake%20CaaS/v1/bundle/master/openapi.yaml
  iam-scim-latest: https://api.redoc.ly/registry/hpe/HPE%20GreenLake%20IAM%20-%20SCIM/v2/bundle/master/openapi.yaml
  iam-rbac-latest: https://api.redoc.ly/registry/hpe/HPE%20-%20GreenLake%20IAM%20-%20RBAC/v1alpha2/bundle/master/openapi.yaml
  mlops-latest: https://api.redoc.ly/registry/hpe/MLOps/v1alpha1/bundle/master/openapi.yaml
  # add links to definitions in our API registry by using a fully qualified URL.

stylesheets:
  - https://fonts.googleapis.com/css?family=Roboto:300,400,600,700
  - https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700&display=swap

nav:

  - label: HPE Redfish implementation
    href: 'https://www.hpe.com/us/en/servers/restful-api.html'
    external: true

  - label: About
    href: 'https://hpe.com/'
    external: true

  - search: true

footer:
  copyrightText: © Copyright 2017-2021 Hewlett Packard Enterprise Development LP
  columns:
    - group:
      items:
        - label: Privacy Policy
          href: 'https://client.greenlake.hpe.com/login#'
          external: true
    - group:
      items:
        - label: Cookies
          href: 'https://www.hpe.com/us/en/legal/privacy.html#accordion-accordioncontainerco-4'
          external: true
    - group:
      items:
        - label: Terms of Use
          href: 'https://www.hpe.com/us/en/about/legal/terms-of-use.html'
          external: true
    - group:
      items:
        - label: Do Not Sell My Personal Information
          href: 'https://www.hpe.com/us/en/privacy/personal-information.html'
          external: true

