meta:
  title: HPE Redfish Developer Central 
  description:  HPE Redfish API implementations documentation.
  siteUrl: https://www.hpe.com
headerIcon: ./images/hpe.svg
enableToc: true
oasDefinitions:
  # add links to definitions in our API registry by using a fully qualified URL.
  #mlops-latest: https://api.redoc.ly/registry/hpe/MLOps/v1alpha1/bundle/master/openapi.yaml
  #redfishiLO5RefDoc: https://api.redoc.ly/registry/hpe/redfishiLO5RefDoc/v1alpha1/bundle/master/api/openapi/ilo5-openapi.yaml
  redfishiLO5RedfDoc: https://api.redoc.ly/registry/hpe/redfishiLO5RefDoc/v1Alpha1/bundle/main/openapi.yaml

stylesheets:
  - https://fonts.googleapis.com/css?family=Roboto:300,400,600,700
  - https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700&display=swap

nav:

  - label: HPE Redfish implementation
    href: 'https://www.hpe.com/us/en/servers/restful-api.html'
    external: true

  - label: About
    href: 'https://hpe.com/'
    external: true

  - search: true

footer:
  copyrightText: © Copyright 2017-2021 Hewlett Packard Enterprise Development LP
  columns:
    - group:
      items:
        - label: Privacy Policy
          href: 'https://client.greenlake.hpe.com/login#'
          external: true
    - group:
      items:
        - label: Cookies
          href: 'https://www.hpe.com/us/en/legal/privacy.html#accordion-accordioncontainerco-4'
          external: true
    - group:
      items:
        - label: Terms of Use
          href: 'https://www.hpe.com/us/en/about/legal/terms-of-use.html'
          external: true
    - group:
      items:
        - label: Do Not Sell My Personal Information
          href: 'https://www.hpe.com/us/en/privacy/personal-information.html'
          external: true

