seo: 
  keywords: 'Redfish, RESTful API'
  lang: en-US
envVariablesAllowedClientSide:
  - LATEST_FW_VERSION
  - LATEST_ILO_GEN_VERSION
  - LATEST_ILO6_FW_VERSION
  - LATEST_ILO7_FW_VERSION
  - LATEST_ILO5_FW_VERSION
  - LATEST_PYTHON_LIBRARY_VERSION
postBodyScripts:
  - 'https://www.hpe.com/global/metrics/easy/basic_measurement.js'

excludeFromSearch: true

meta:
  title: HPE server management with Redfish®
  description: HPE Redfish services and clients documentations.
  siteUrl: https://tbd.developer.hpe.com
  lang: en-US

logo:
  image: './images/hpe.svg'
  altText: 'Hewlett Packard Enterprise'

linkChecker:
  severity: warning
  options:
    # Refer to https://github.com/wjdp/htmltest#basic-options for options
    LogLevel: 3
    ExternalTimeout: 10
    DirectoryPath: "docs"
    EnforceHTTPS: false
    IgnoreAltMissing: true
    IgnoreAltEmpty: true
    CheckExternal: false
    IgnoreURLs:
        # Links with timeout issues
        - "https://www.hpe.com/info/resttool"
        - "https://www.hpe.com/us/en/hpe-greenlake-compute-ops-management.html"
        - "^.*proxy.*$"
        # Remove these if/when the Redocly link checker handles rate limiting:
        - "docs.github.com"
        - "github.com"
        # Remove directories containing autogenerated files. Autogenerated files contain
        # http:// and non-relevant URLs like http://IPv6:port.
        # Unfortunately it is not possible to exclude files. In our case by excluding iloX directories
        # we exclude as well the index.md file. Not a big deal anyway.
    IgnoreDirs:
        - "ilo5"
        - "ilo6"
        - "ilo7"




#oasDefinitions:
  # Add links to local swagger/openapi file
  #redfishiLO6110RefDoc: openapi/ilo6_110/ilo6110-openapi.yaml
  #redfishiLO5255RefDoc: openapi/ilo5_255/ilo5255-openapi.yaml
  #redfishDmtfRefDoc: https://api.redoc.ly/registry/hpe/RedfishDmtfRefDoc/internalv1/bundle/main/openapi.yaml
  #
stylesheets:
  - 'https://fonts.googleapis.com/css?family=Roboto:300,400,600,700'
  - 'https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700&display=swap'
  - './static/styleOverrides.css'

scripts:
  - './scripts/ucep-loader.js'
  - 'https://h50007.www5.hpe.com/hfws-static/js/framework/jquery/v-3-6-0/jquery.js'

toc:
  enable: true
  maxDepth: 2

nav:
  - search: true
  - label: 'Redfish® Standard'
    href: 'https://www.dmtf.org/standards/redfish'
    external: true

analytics:
  # See doc at: https://redocly.com/docs/developer-portal/configuration/siteconfig/analytics/#google-analytics
  #
  gtag:
    trackingIds:
      - "G-RF9XF1EZ3E" #Google Analytics / GA
    gtagConfig:
      anonymize_ip: true
      cookie_expires: 0
    # This object is used for configuration specific to this plugin
    pluginConfig:
      # Puts tracking script in the head instead of the body
      head: true
      # Setting this parameter is also optional
      respectDNT: true
      # Avoids sending pageview hits from custom paths
      # exclude: ["/preview/**", "/do-not-track/me/too/"]

