#!/usr/bin/bash

# This script adapts the Slate-markdown formated msgregs.md (autogenerated) file 
# into a Redocly-markdown formated file. The main purpose is to:
#  * Prepend the Redocly front matter section (toc...)
#  * Prepend a header 1 and associated lightintroduction.

# Requirements: 
# * Input file ($MsgRegistryFile=_raw_iloG_msgregsVVV.md) automatically generated using the tools/make.ps1 script.

# This script MUST be launched by _script_wrapper.sh, which contains 
# suitable configuration variables.
# 
# ToDo
#     * Adapt to Reunite/Realm/Markdoc

# version 0.1

# Local Variables
InputFile=$MsgRegistryFile
OutputFile="${WorkingDirectory}/${iLOGen}_msgregs${iLOVersion}.md"

# The following SEO variable contains Redocly front-end matter directives
SEO="---
seo:
  title: ${ilogen} v${iLOVersion} Error messages
toc:
  enable: false
disableLastModified: false
---\n
"
Header1Title="# Response message definitions of ${ilogen} v${iLOFwVersion}\n\n"

FileDescription="This section is a reference for the defined message registry entries in HPE ${ilogen} version ${iLOFwVersion}. \
Redfish responses are discussed in the [error responses](/docs/concepts/errorresponses.md) section.\n" 

# OutputFile creation with seo, title and description strings.
echo -e "${SEO}${Header1Title}${FileDescription}" > $OutputFile
cat $InputFile >> $OutputFile


