#!/usr/bin/bash

# This script adapts the Slate-markdown formated resmap.md (autogenerated) file 
# into a Redocly-markdown formated file. The main purpose is to:
#  * Prepend the Redocly front matter section (toc...)
#  * Change fragments: The rendered Slate document is a single html document.
#                      The Redocly document is composed of several html files. Hence fragments mus be re-aligned.

# Requirements: 
# * Input file ($resmapFile=_raw_iloG_resmap.md) automatically generated using the tools/make.ps1 script.

# This script MUST be launched by _script_wrapper.sh, which contains 
# suitable configuration variables.

# ToDo:
#     * test return codes of important commands (i.e. sed)

# version: 0.55

# Local Variables
ResourceFiles=$(ls ${WorkingDirectory}/${iLOGen}_*_resourcedef*.md)
InputFile=$ResmapFile
OutputFile="${WorkingDirectory}/${iLOGen}_resmap${iLOVersion}.md"

# Remove CR chars in InputFile if any
dos2unix $InputFile

# The following SEO variable contains Redocly front-end matter directives
if [ RedoclyRealm == "false" ] ; then
  SEO="---
seo:
  title: ${ilogen} version ${iLOFwVersion} Resource map
toc:
  enable: false
disableLastModified: false
---\n
"
else
  SEO="---
seo:
  title: ${ilogen} version ${iLOFwVersion} Resource map
markdown:
  toc:
    hide: true
    depth: 2
  lastUpdateBlock:
    hide: false
breadcrumbs:
  hide: false
---\n
"
fi

Header1Title="# Resource map of ${ilogen} v${iLOFwVersion}\n\n"
FileDescription="The following table lists HPE iLO Redfish resource types and their associated URIs.\
\n\n\
Refer to the [data types and collection](/docs/concepts/dataTypesAndCollections.md) section for more information on Redfish data types and collections.\n\n"

# The following variable lists duplicated types pointing to the same URI in the resourcedefns file.
# We will have to keep only one URI.
ExcludeTypeList="JsonSchemaFile"

# OutputFile creation with seo, title and description strings.
echo -e "${SEO}${Header1Title}${FileDescription}" > $OutputFile
cat $InputFile >> $OutputFile

# Fix the SwitchCollection entry:
# Replace: Collection of [SwitchCollection](#switchcollection-switchcollection)
# with: Collection of [Switch](#switch-v1_9_1-switch)
# Extract Switch schema version first
switchVersion="$(grep '\[Switch\](#switch-v.*-switch)' $OutputFile  |  grep -o 'v[1-9]*_[0-9]*_[0-9]*')"
sed -i -e "s?Collection of \[SwitchCollection\](#switchcollection-switchcollection)?Collection of [Switch](#switch-${switchVersion}-switch)?g" $OutputFile

# For each resource type, find its resource definitions file:
for type in $TypeList ; do
  echo -e "  Processing $type"
 
  if [ $? != 0 ] ; then
    echo "Problem with ${type}. Discarding"
    continue
  fi

  # find where is described this type of resource.
  TmpVar=$(grep -l "^## ${type}$" $ResourceFiles)

  # if $type is present in the ExcludeTypeList, because it is listed
  # several times as a "## type" header, then we need to select
  # only one file (i.e. the first one). If we don't do that, the following 
  # basename command fails.
  if [[ "$ExcludeTypeList" =~ "$type"  ]] ; then
     TmpVar=$(grep -l "^## ${type}$" $ResourceFiles | head -1)
     echo -e "${type} is mentioned in several files. Selecting the first one:\n $TmpVar "
  fi

  IsIn=$(basename -s ".md" $TmpVar 2>/dev/null)
  if [ $? != 0 ] ; then
    echo -e "Problem with ${type}. Discarding.\n${TmpVar}"
    continue
  fi


#  The following sed command modifies links/fragments pointing to the resource definition files:
# 1. from [ServiceRoot](#serviceroot-v1_13_0-serviceroot) to [ServiceRoot](../${iLOGen}_other_resourcedefns105/#serviceroot). NOTE: "../" must be removed in Reunite/Realm/Markdoc.
# 2. from: "|Collection of [Certificate](#certificate-v1.0.0_certificate)" to "|Collection of [Certificate](../${iLOGen}_other_resourcedefns105/#certificatecollection)"

if [ $RedoclyRealm == false ] ; then
  sed -i -e "s?\(|\[${type}\]\)(\(#.*\)-\(v.*\)-\(.*\))?\1(../${IsIn}/\2)?"                         \
      -e "s?\(|Collection of \[${type}\]\)(\(#.*\)-\(v.*\)-\(.*\))?\1(../${IsIn}/\2collection)?"    \
      $OutputFile
else
  sed -i -e "s?\(|\[${type}\]\)(\(#.*\)-\(v.*\)-\(.*\))?\1(${IsIn}/\2)?"                         \
      -e "s?\(|Collection of \[${type}\]\)(\(#.*\)-\(v.*\)-\(.*\))?\1(${IsIn}/\2collection)?"    \
      $OutputFile
fi
done

# Fix Oem/Hpe collections that don't follow the schema/schemacollection paradigm.
# NOTES: 
#       * The Sensor substitution may be removed when the FallBackSensor collection is correctly implemented.
sed -i -e '1,$s?/#hpeusbportcollection)|$?/#hpeusbportscollection)|?g ;
           1,$s?/#hpecomponentupdatetaskcollection)|$?/#hpecomponentupdatetaskqueuecollection)|?g ;
           1,$s?/#hpeusbdevicecollection)|$?/#hpeusbdevicescollection)|?g ;
           1,$s?/#hpesnmpusercollection)|?/#hpesnmpuserscollection)|?g ;
           1,$s?Sensor](ilo\(.\)_other_resourcedefns\(...\)/#sensorcollection?FallBackSensor](ilo\1_hpe_resourcedefns\2/#hpefallbacksensorcollection?g' $OutputFile

# To be consistent with other entries in this resmap file:
# * Need to cleanup wrong FallBackSensorCollection that points badly to the sensor collection.
sed -i -e '/{item}\/sensors`|Collection of \[FallBackSensor\]/d' $OutputFile

# * Need to double check that the "FallBack" string is only present once in the Collection line.
#   If it is present several times, then we need to print a warning.
if [[ $(grep -i -c 'FallBackSensor'  $OutputFile) -gt 1  ]] ; then
  echo "^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^"
  echo -e "Warning: The string \`FallBackSensor\` is present more than once in the file $OutputFile.\n\
  Please check the file and remove the duplicates.\n"
  echo "^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^"
fi 

# * if `Collection of FallBackSensor` is present, then insert a line pointing to its members.
if grep -q 'fallbacksensors`|Collection of \[FallBackSensor' $OutputFile ; then
  echo -e "\nInserting a line pointing to the [FallBack]Sensor members."
  sed -i -e '/Collection of \[FallBackSensor/a\|`/redfish/v1/chassis/{item}/sensors/{item}`|[FallBackSensor]('${iLOGen}'_other_resourcedefns'${iLOVersion}'/#sensor)|' $OutputFile
fi

# Fixing AppAccounts
# For some reasons, final ilo7+_resmapXYZ.md files contain bad AppAccounts entries.
echo -e "\nFixing AppAccounts if needed..."

# /accounts`|Collection of [HpeiLOAppAccount](ilo7_hpe_resourcedefns113/#hpeiloappaccount)|
# should be:
# /accounts`|Collection of [ManagerAccount](ilo7_manager_resourcedefns113/#manageraccountcollection)|
sed -i -e 's?/accounts`|Collection of \[HpeiLOAppAccount\](\(.*\)_hpe_resourcedefns\(.*\)/#hpeiloappaccountcollection)|?/accounts`|Collection of [ManagerAccount](\1_manager_resourcedefns\2/#manageraccountcollection)?g' $OutputFile

# The following must be re-worked.
# May be just add an `HpeiLOAppaccountCollection` in the hpe_resourcredefns file?
# |`/redfish/v1/accountservice/Oem/Hpe/appaccounts`|Collection of [HpeiLOAppAccount](ilo7_hpe_resourcedefns113/#hpeiloappaccountcollection)|
# should be:
# |`/redfish/v1/accountservice/Oem/Hpe/appaccounts`|Collection of [HpeAppAccount](ilo7_hpe_resourcedefns113/#hpeappaccountcollection)|
#sed -i -e 's?/appaccounts`|Collection of \[HpeiLOAppAccount\](\(.*\)_hpe_resourcedefns\(.*\)/#hpeiloappaccountcollection)?/appaccounts`|Collection of [HpeAppAccount](\1_hpe_resourcedefns\2/#hpeappaccountcollection)?g' $OutputFile

# The following must be re-worked.
# This may not be needed anymore...
# |`/redfish/v1/accountservice/Oem/Hpe/appaccounts/{item}`|[HpeiLOAppAccount](ilo7_hpe_resourcedefns113/#hpeiloappaccount)|
# should be:
#|`/redfish/v1/accountservice/Oem/Hpe/appaccounts/{item}`|[HpeAppAccount](#hpeappaccount)|
#sed -i -e 's?/appaccounts/{item}`|\[HpeiLOAppAccount\](\(.*\)_hpe_resourcedefns\(.*\)/#hpeiloappaccount)?/appaccounts/{item}`|[HpeAppAccount](\1_hpe_resourcedefns\2/#hpeappaccount)?g' $OutputFile

echo -e "Cleanup: Removing:\n"
echo -e "\t$ResourcesFile"
rm $ResourcesFile &> /dev/null

