#!/usr/bin/bash

# This script splits the autogenerated resourcedefns.md file into several 
# smaller files. The reason is because one single resourcedefns.md file is
# too big for Redocly which fails with a "Maximum stack size exceeded"
# error message.

# This script MUST be launched by _script_wrapper.sh, which contains 
# configuration variables.

# Todo:
#       * Test return code of all important commands. I.e. sed.

#
# Prepare input file
#
rm $OtherResourcesFile &> /dev/null
separator="==============="
sed -i "/^## /i ${separator}" $ResourcesFile         # Insert a separator between resource definitions
cp $ResourcesFile $OtherResourcesFile

# Main loop
for list in $typeLists ; do
  OutputFile="${WorkingDirectory}/_${iLOGen}_resourcedefns${iLOVersion}.${list}"
  rm $OutputFile &> /dev/null    # just in case

  echo "Extracting $list data types into $(basename $OutputFile)"
  for type in $(eval echo \$$list) ; do
    echo "  Processing $type resource"
    # Extract $type from input file and append it to $OutputFile
    sed -n -e "/^## ${type}\./,/${separator}/p" $ResourcesFile | head -n -1 >> $OutputFile
    # Remove $type from input file.
    sed -i "/^## ${type}/,/${separator}/d" $OtherResourcesFile
  done
  echo
done

#
# Process other/remaining data types that have not been processed in main loop above.
#
# Create the list of remaining data types
other=$(grep  '^## ' $OtherResourcesFile | awk '/^## / {print $NF}' $OtherResourcesFile | cut -d'.' -f 1 | sort -u)
OutputFile="${WorkingDirectory}/_${iLOGen}_resourcedefns${iLOVersion}.other"
rm $OutputFile &> /dev/null   # just in case

echo "Extracting other/remaining data types into $(basename $OutputFile) "
for type in $other ; do
  echo "  Processing $type resource"
  # Extract $type from input file and append it to $OutputFile
  sed -n "/^## ${type}\./,/${separator}/p" $ResourcesFile >> $OutputFile
done

# Cleanup files. May be not needed as we remove these file in the wrapper.
sed -i "s/${separator}//" $ResourcesFile      
sed -i "s/${separator}//" $OtherResourcesFile
sed -i "s/${separator}//" $OutputFile
