#!/bin/bash

# This script helps for the preparation of the environment for
# the creation of a new Fw version documentation or
# for the re-publishing of an old deleted fw documentation.
#
# It does not do everything, but 
# saves time when it comes to the inclusion of the new pointers
# in the sidebar menu...

# Version 0.2

# This script is the original of
# /Git-Repo/CloneOfPrivate-hpe-ilo-redocly/docs/_scripts/_PrepareFwEnv.sh

# NOTES:
#      * Prior to run this script:
#        - Clone the upstream hpe-ilo-redocly. It should be already done if you are reading
#          this file from your laptop.
#        - Checkout a new branch that will host a ready to be rendered firmware version
#          ex: git checkout -b iLO5-314
#        - Place the three raw autogenerated files in a location of your choice with correct name.
#          ex: /tmp/RawFilesLocation/_raw_${iLOGen}*-bck
#          In case of re-publishing a deleted fw version

# ToDo:
#     * This script is not bullet proofed

################  Modify the following four variables for a new fw version  #########################
export ilogen="iLO 5"
export iLOFwVersion="3.14"

# Read the above NOTES to understand the content of the following 2 locations 
export RepoLocation="/cygdrive/c/Git-repo/CloneOfPrivate-hpe-ilo-redocly"
export RawFilesLocation="/tmp/RawFilesLocation"

################ Below variables don't need to be modified #######################
export iLOGen=$(echo ${ilogen,,} | tr -d ' ')
export ILOGEN="$(echo ${iLOGen^^} )"
export iLOVersion=$(echo $iLOFwVersion | tr -d '.')
export let Gen=$(echo $iLOGen | tr -d '[:alpha:]'  )

export WorkingDirectory="$RepoLocation/docs/redfishServices/ilos/${iLOGen}/${iLOGen}_${iLOVersion}"

# In case of a new FW version to be documented, it is needed to create the target directory.
# In case of an old FW version removed by _script_wrapper.sh, the directory should be there.
# If it is not there, create it manually and re-run this script and populate it
# manually with the raw files.
if [ ! -d "$WorkingDirectory" ] ; then
  echo "Creating target directory: $(basename $WorkingDirectory)"
  mkdir -p $WorkingDirectory
  Pattern="changelog.md" # group menu will have to be placed below string $Pattern in sidebars.yaml
else
  Pattern="#AppendAbove"  # group menu will have to be placed above string $Pattern in sidebars.yaml
fi

# Populate temporary _index.md, Sidebar-block.yaml files and create README.md file.
cd $WorkingDirectory
rm README.md _index.md Sidebar-block.yaml ../tmpfile.yaml &> /dev/null

cat > _index.md << __EOF__
---
markdown:
  toc:
    hide: true
    depth: 3
  lastUpdateBlock:
    hide: true
breadcrumbs:
  hide: false
seo:
  title: HPE ${ilogen} v${iLOFwVersion} reference documents
---

# HPE ${ilogen} v${iLOFwVersion} reference documents overview

HPE iLO Redfish reference documents consist of three documents bound to a specific iLO firmware version:

- [Resource map](/docs/redfishservices/ilos/${iLOGen}/${iLOGen}_${iLOVersion}/${iLOGen}_resmap${iLOVersion}/)
- Resource definitions (i.e. [ServiceRoot](/docs/redfishservices/ilos/${iLOGen}/${iLOGen}_${iLOVersion}/${iLOGen}_serviceroot_resourcedefns${iLOVersion}/))
- [Error messages](/docs/redfishservices/ilos/${iLOGen}/${iLOGen}_${iLOVersion}/${iLOGen}_msgregs${iLOVersion}/)

The Resource map reference document provides the list of [data types and collection](/docs/concepts/datatypesandcollections/) URIs implemented in the iLo firmware. For each data type, it provides a the 
link to the associated detailed description in the resource definition section.

The resource definitions documents contain the detailed description of all Redfish resources and properties. Those definitions can be grouped under a single menu entry. For example, the [Manager](/docs/redfishservices/ilos/${iLOGen}/${iLOGen}_${iLOVersion}/${iLOGen}_manager_resourcedefns${iLOVersion}/) resource definitions entry contains definitions of the \`ManagerCollection\`, \`Manager\`, \`ManagerAccountCollection\`, etc. Similarly the [HPE OEM extensions](/docs/redfishservices/ilos/${iLOGen}/${iLOGen}_${iLOVersion}/${iLOGen}_hpe_resourcedefns${iLOVersion}/) contains the description of all the HPE OEM extensions.

However, other resource definitions documents can contain the definitions of a single resource (i.e. [Bios](/docs/redfishservices/ilos/${iLOGen}/${iLOGen}_${iLOVersion}/${iLOGen}_bios_resourcedefns${iLOVersion})).

{% admonition type="success" name="TIP" %}
Use the search box in the upper right corner of the main pane to find all the sections containing a specific keyword.
{% /admonition %}

The Error Messages section contains the description, format, severity and (if applicable) a resolution hint of the HTTP response bodies.

__EOF__

# Substitute variables in _index.md and move it to its final name.
envsubst < _index.md > index.md

cat > README.md << __EOF__
---
excludeFromSearch: true
---

# README

Read the [docs/README.md](../../../../README.md) file for an explanation of the files present in this folder.

__EOF__

cat > Sidebar-block.yaml << __EOF__
- group: ${ilogen} v${iLOFwVersion} Reference documents
  expanded: false
  items:
    - label: Reference documents Overview
      page: ${iLOGen}_${iLOVersion}/index.md
    - label: Resource map
      page: ${iLOGen}_${iLOVersion}/${iLOGen}_resmap${iLOVersion}.md
    - group: Resource definitions
      expanded: false
      items:
        - label: ServiceRoot
          page: ${iLOGen}_${iLOVersion}/${iLOGen}_serviceroot_resourcedefns${iLOVersion}.md   
        - label: Bios
          page: ${iLOGen}_${iLOVersion}/${iLOGen}_bios_resourcedefns${iLOVersion}.md
        - label: Manager
          page: ${iLOGen}_${iLOVersion}/${iLOGen}_manager_resourcedefns${iLOVersion}.md       
        - label: ComputerSystem
          page: ${iLOGen}_${iLOVersion}/${iLOGen}_computersystem_resourcedefns${iLOVersion}.md
        - label: Chassis
          page: ${iLOGen}_${iLOVersion}/${iLOGen}_chassis_resourcedefns${iLOVersion}.md       
        - label: Network
          page: ${iLOGen}_${iLOVersion}/${iLOGen}_network_resourcedefns${iLOVersion}.md       
        - label: Storage
          page: ${iLOGen}_${iLOVersion}/${iLOGen}_storage_resourcedefns${iLOVersion}.md       
        - label: HPE Oem extensions
          page: ${iLOGen}_${iLOVersion}/${iLOGen}_hpe_resourcedefns${iLOVersion}.md
        - label: Other resource definitions
          page: ${iLOGen}_${iLOVersion}/${iLOGen}_other_resourcedefns${iLOVersion}.md
        #- label: Event definitions
        #  page: docs/ilos/${iLOGen}${iLOVersion}/${iLOGen}_events${iLOVersion}.md
    - label: Error messages
      page: ${iLOGen}_${iLOVersion}/${iLOGen}_msgregs${iLOVersion}.md
__EOF__


# Update iloX.sidebars.yaml
echo "Updating ${iLOGen}.sidebars.yaml" 
envsubst < Sidebar-block.yaml > _Sidebar-block.yaml
mv _Sidebar-block.yaml Sidebar-block.yaml

case "$Pattern" in  
  changelog*)
    echo -e "\tInserting new sidebar block after changelog"
    mv  ${RepoLocation}/docs/redfishServices/ilos/${iLOGen}/${iLOGen}.sidebars.yaml ../tmpfile.yaml
    awk \/${Pattern}'/ {system("cat 'Sidebar-block.yaml'"); next} 1' \
    ../tmpfile.yaml > ${RepoLocation}/docs/redfishServices/ilos/${iLOGen}/${iLOGen}.sidebars.yaml
    echo -e "\tCopying raw files to destination directory"
    cp ${RawFilesLocation}/_raw_${iLOGen}*-bck ${WorkingDirectory}/. 
    ;;
  *AppendAbove)
    echo -e "\tRestoring an old sidebar block"
    sed -i -e "/${Pattern}/ {e cat Sidebar-block.yaml}" ${RepoLocation}/docs/redfishServices/ilos/${iLOGen}/${iLOGen}.sidebars.yaml
    ;;
  *)
    echo "Problem in ${iLOGen}.sidebars.yaml: Don't now where to include new sidebar block"
    ;;
esac

echo "Cleanup..."
rm _index.md Sidebar-block.yaml ../tmpfile.yaml &> /dev/null

exit 0



